<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Protocol Buffer 3</string>
    <key>scopeName</key>
    <string>source.proto</string>
    <key>fileTypes</key>
    <array>
      <string>proto</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#syntax</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#package</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#optionStmt</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#message</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#enum</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#service</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.proto</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.proto</string>
            <key>begin</key>
            <string>//</string>
            <key>end</key>
            <string>$\n?</string>
          </dict>
        </array>
      </dict>
      <key>syntax</key>
      <dict>
        <key>match</key>
        <string>\s*(syntax)\s*=\s*("proto[23]")\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.proto.syntax</string>
          </dict>
        </dict>
      </dict>
      <key>package</key>
      <dict>
        <key>match</key>
        <string>\s*(package)\s+([\w.]+)\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.unquoted.proto.package</string>
          </dict>
        </dict>
      </dict>
      <key>import</key>
      <dict>
        <key>match</key>
        <string>\s*(import)\s+(weak|public)?\s*("[^"]+")\s*;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.proto.import</string>
          </dict>
        </dict>
      </dict>
      <key>optionStmt</key>
      <dict>
        <key>begin</key>
        <string>(option)\s+(\w+|\(\w+(\.\w+)*\))(\.\w+)*\s*=</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#subMsgOption</string>
          </dict>
        </array>
      </dict>
      <key>subMsgOption</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\w+)\s*:</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.other.proto</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
        </array>
      </dict>
      <key>fieldOptions</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#subMsgOption</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionName</string>
          </dict>
        </array>
      </dict>
      <key>optionName</key>
      <dict>
        <key>match</key>
        <string>(\w+|\(\w+(\.\w+)*\))(\.\w+)*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.other.proto</string>
          </dict>
        </dict>
      </dict>
      <key>message</key>
      <dict>
        <key>begin</key>
        <string>(message|extend)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.message.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#reserved</string>
          </dict>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enum</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionStmt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oneof</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#mapfield</string>
          </dict>
        </array>
      </dict>
      <key>reserved</key>
      <dict>
        <key>begin</key>
        <string>(reserved)\s+</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(\d+)(\s+(to)\s+(\d+))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.proto</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.proto</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.proto</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
        </array>
      </dict>
      <key>field</key>
      <dict>
        <key>begin</key>
        <string>\s*(optional|repeated|required)?\s*\b([\w.]+)\s+(\w+)\s*=\s*(\d+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.modifier.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.proto</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fieldOptions</string>
          </dict>
        </array>
      </dict>
      <key>mapfield</key>
      <dict>
        <key>begin</key>
        <string>\s*(map)\s*&lt;\s*([\w.]+)\s*,\s*([\w.]+)\s*&gt;\s+(\w+)\s*=\s*(\d+)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type.proto</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.proto</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fieldOptions</string>
          </dict>
        </array>
      </dict>
      <key>oneof</key>
      <dict>
        <key>begin</key>
        <string>(oneof)\s+([A-Za-z][A-Za-z0-9_]*)\s*\{?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#optionStmt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#field</string>
          </dict>
        </array>
      </dict>
      <key>enum</key>
      <dict>
        <key>begin</key>
        <string>(enum)(\s+)([A-Za-z][A-Za-z0-9_]*)(\s*)(\{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#reserved</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionStmt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>([A-Za-z][A-Za-z0-9_]*)\s*=\s*([0-9]*)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>constant.other.proto</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.proto</string>
              </dict>
            </dict>
            <key>end</key>
            <string>;</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#fieldOptions</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>service</key>
      <dict>
        <key>begin</key>
        <string>(service)\s+([A-Za-z][A-Za-z0-9_.]*)\s*\{?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.class.message.proto</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionStmt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#method</string>
          </dict>
        </array>
      </dict>
      <key>method</key>
      <dict>
        <key>begin</key>
        <string>(rpc)\s+([A-Za-z][A-Za-z0-9_]*)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.other.proto</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}|;</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#optionStmt</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rpcKeywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ident</string>
          </dict>
        </array>
      </dict>
      <key>rpcKeywords</key>
      <dict>
        <key>match</key>
        <string>\b(stream|returns)\b</string>
        <key>name</key>
        <string>keyword.other.proto</string>
      </dict>
      <key>ident</key>
      <dict>
        <key>match</key>
        <string>[A-Za-z][A-Za-z0-9_]*</string>
        <key>name</key>
        <string>entity.name.class.proto</string>
      </dict>
      <key>constants</key>
      <dict>
        <key>match</key>
        <string>\b(true|false|max|[A-Z_]+)\b</string>
        <key>name</key>
        <string>constant.language.proto</string>
      </dict>
      <key>storagetypes</key>
      <dict>
        <key>match</key>
        <string>\b(double|float|int32|int64|uint32|uint64|sint32|sint64|fixed32|fixed64|sfixed32|sfixed64|bool|string|bytes)\b</string>
        <key>name</key>
        <string>storage.type.proto</string>
      </dict>
      <key>string</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>name</key>
        <string>string.quoted.double.proto</string>
      </dict>
      <key>number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.proto</string>
        <key>match</key>
        <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
      </dict>
    </dict>
  </dict>
</plist>